[alembic]
script_location = alembic

sqlalchemy.url = postgresql+asyncpg://postgres:postgres@postgres:5432/bb_kz

[loggers]
keys = root,sqlalchemy,alembic
level = INFO
handlers = console
qualname = 

[handlers]
keys = console
handlers = console
class = StreamHandler
args = (sys.stderr,)

[formatters]
keys = generic
formatters = generic
class = %(class)s
format = %(levelname)-5.5s [%(name)s] %(message)s

